table dim_promotion
	excludeFromModelRefresh
	lineageTag: cd02d20a-2b19-4f10-894f-e8fc70bcacb5

	column promotion_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fc92d850-f124-4202-967b-865221ecac9b
		summarizeBy: sum
		sourceColumn: promotion_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column promotion_id
		dataType: string
		lineageTag: 1bfc721f-0b49-4e00-b2fa-4f0ef738a4f7
		summarizeBy: none
		sourceColumn: promotion_id

		annotation SummarizationSetBy = Automatic

	column promotion_name
		dataType: string
		lineageTag: 85def36d-a3ce-4c8b-ba0d-6f75267661f9
		summarizeBy: none
		sourceColumn: promotion_name

		annotation SummarizationSetBy = Automatic

	column campaign_type
		dataType: string
		lineageTag: 3ae3fa1d-9fa4-4f3d-9e07-c8e36ff6978f
		summarizeBy: none
		sourceColumn: campaign_type

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5c9840ce-ec3b-435d-b475-06e4b2cea230
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5ff2ce31-b278-4227-8c27-1c26b19bb3c0
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column target_segment
		dataType: string
		lineageTag: 8e597b4f-4123-4fd1-bd67-5913631d9e55
		summarizeBy: none
		sourceColumn: target_segment

		annotation SummarizationSetBy = Automatic

	column discount_type
		dataType: string
		lineageTag: 7a29bcc1-799b-469b-b592-415c85f286bb
		summarizeBy: none
		sourceColumn: discount_type

		annotation SummarizationSetBy = Automatic

	column planned_lift
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e939c21f-9429-4ccb-9e3e-040b7a4d3f2c
		summarizeBy: sum
		sourceColumn: planned_lift

		annotation SummarizationSetBy = Automatic

	column planned_budget
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e69727b6-9f80-4f8e-9144-fdf6dc48fc2d
		summarizeBy: sum
		sourceColumn: planned_budget

		annotation SummarizationSetBy = Automatic

	column promotion_duration = ```
			DATEDIFF(dim_promotion[start_date], dim_promotion[end_date], DAY) 
			```
		formatString: 0
		lineageTag: 4c492f28-906d-48f1-9204-f724fff497c4
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition dim_promotion = m
		mode: import
		queryGroup: orders_star_schema
		source =
				let
				    Source = Promotion,
				    #"Added Index" = Table.AddIndexColumn(Source, "Index", 0, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "promotion_key"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"promotion_key", "PromotionID", "Name", "CampaignType", "StartDate", "EndDate", "TargetSegment", "DiscountType", "PlannedLift%", "PlannedBudget"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"PromotionID", "promotion_id"}, {"Name", "promotion_name"}, {"CampaignType", "campaign_type"}, {"StartDate", "start_date"}, {"EndDate", "end_date"}, {"TargetSegment", "target_segment"}, {"DiscountType", "discount_type"}, {"PlannedLift%", "planned_lift"}, {"PlannedBudget", "planned_budget"}}),
				    #"Divided Column" = Table.TransformColumns(#"Renamed Columns1", {{"planned_lift", each _ / 100, type number}})
				in
				    #"Divided Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

