table dim_payment_type
	excludeFromModelRefresh
	lineageTag: c54266c9-3a34-47b6-b54a-9f9d089d3f98

	column payment_type_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: dfb714bd-7d28-479c-a5de-01ec93eba0fc
		summarizeBy: none
		sourceColumn: payment_type_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column payment_type
		dataType: string
		lineageTag: b0d7a42b-2cdd-467c-8d28-22eab2ab8a4d
		summarizeBy: none
		sourceColumn: payment_type

		annotation SummarizationSetBy = Automatic

	partition dim_payment_type = m
		mode: import
		queryGroup: orders_star_schema
		source =
				let
				    Source = OrderHeader,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"PaymentType"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 0, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "PaymentType"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "payment_type_key"}, {"PaymentType", "payment_type"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

