table fact_order_return
	lineageTag: 1f620365-0fdd-414d-a33e-10029a244b39

	column order_return_key
		dataType: int64
		formatString: 0
		lineageTag: b393fbb4-4018-4adb-8873-f721a8fc7ca1
		summarizeBy: sum
		sourceColumn: order_return_key

		annotation SummarizationSetBy = Automatic

	column returnd_id
		dataType: string
		lineageTag: 991b4c43-0716-45b4-a172-865bd62651ed
		summarizeBy: none
		sourceColumn: returnd_id

		annotation SummarizationSetBy = Automatic

	column order_line_id
		dataType: string
		lineageTag: a3a894e8-fbed-4578-b004-1836893599f9
		summarizeBy: none
		sourceColumn: order_line_id

		annotation SummarizationSetBy = Automatic

	column return_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4e919a8a-2a1f-41cb-8e6b-cbdce4341d51
		summarizeBy: none
		sourceColumn: return_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column return_disposition_key
		dataType: int64
		formatString: 0
		lineageTag: a358340b-3f63-47b4-b08a-87c2a96840cf
		summarizeBy: none
		sourceColumn: return_disposition_key

		annotation SummarizationSetBy = Automatic

	column return_condition_key
		dataType: int64
		formatString: 0
		lineageTag: 4f1f7e71-584d-4ed7-8851-5f275c032aa3
		summarizeBy: none
		sourceColumn: return_condition_key

		annotation SummarizationSetBy = Automatic

	column return_reason_key
		dataType: int64
		formatString: 0
		lineageTag: 905830db-cf02-4a07-b69c-4d95270ab0f3
		summarizeBy: none
		sourceColumn: return_reason_key

		annotation SummarizationSetBy = Automatic

	column Refund$
		dataType: double
		lineageTag: 5c265079-d04c-4cd5-bf70-a64298122549
		summarizeBy: sum
		sourceColumn: Refund$

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RestockFee$
		dataType: double
		lineageTag: e47fa86d-2ca2-48fd-aaff-462de969a487
		summarizeBy: sum
		sourceColumn: RestockFee$

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReturnShipCost$
		dataType: double
		lineageTag: 94efaa35-94d1-4852-acee-b4f2bd5348da
		summarizeBy: sum
		sourceColumn: ReturnShipCost$

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_order_return = m
		mode: import
		queryGroup: returns_star_schema
		source =
				let
				    Source = Returns,
				    #"Merged Queries" = Table.NestedJoin(Source, {"ReasonCode"}, dim_return_reason, {"return_reason"}, "dim_return_reason", JoinKind.LeftOuter),
				    #"Expanded dim_return_reason" = Table.ExpandTableColumn(#"Merged Queries", "dim_return_reason", {"return_reason_key"}, {"return_reason_key"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded dim_return_reason", {"Condition"}, dim_return_condition, {"return_condition"}, "dim_return_condition", JoinKind.LeftOuter),
				    #"Expanded dim_return_condition" = Table.ExpandTableColumn(#"Merged Queries1", "dim_return_condition", {"return_condition_key"}, {"return_condition_key"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded dim_return_condition", {"Disposition"}, dim_return_disposition, {"return_disposition"}, "dim_return_disposition", JoinKind.LeftOuter),
				    #"Expanded dim_return_disposition" = Table.ExpandTableColumn(#"Merged Queries2", "dim_return_disposition", {"return_disposition_key"}, {"return_disposition_key"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded dim_return_disposition",{"Disposition", "ReasonCode", "Condition"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"ReturnID", "OrderLineID", "ReturnDate", "return_disposition_key", "return_condition_key", "return_reason_key", "Refund$", "RestockFee$", "ReturnShipCost$"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"ReturnID", "returnd_id"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index",{{"Index", "order_return_key"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"order_return_key", "returnd_id", "OrderLineID", "ReturnDate", "return_disposition_key", "return_condition_key", "return_reason_key", "Refund$", "RestockFee$", "ReturnShipCost$"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns1",{{"OrderLineID", "order_line_id"}, {"ReturnDate", "return_date"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

